contract: bump browserify and exorcist versions
browserify current version depends on an old version of `util`,
which does not have the function `callbackify` defined. This leads
the browser to emit this error:

```
Uncaught (in promise) "TypeError: callbackify is not a function"
```

Also, bump exorcist to match their dependency on browserify 17.0.