Adds missing dependency.
```
npm install @truffle/core
node node_modules/@truffle/core/build/cli.js
> Error: Cannot find module '@truffle/environment'
```