Remove specific presets as it requires user to use babel, and will otherwise error with this error message:
Error: Couldn't find preset "es2015" relative to directory "..."